### ISSUE TITLE
Do not create github status(es) if they already exist

### ISSUE THREAD

**Issue by pkmiec** [appfolio/landa#1]
Currently, the github status(es) are created (as pending) whenever a PR is opened or a new commit is made to a PR. This works well in situations when CI is configured to run on PRs (`refs/pulls/*/head`). However, in cases where CI is configured to run on commits (`refs/head/*`), opening a PR can cause landa to override previously reported status with pending ones. 

We could improve landa to first check whether a status for a sha already exists before creating one.

@balloob thoughts?

**Comment by balloob** [comment]
Sounds good 👍
